title: Ajinkya Awachar
description: Product-focused technology leader building AI-powered, data-driven enterprise solutions.
theme: jekyll-theme-cayman

show_downloads: false
theme: jekyll-theme-minimal  
